#!/bin/bash

set -euo pipefail

echo "Running tests..."

for test in /tests/*.json ; do
	echo "Running test $test"
	(
		IFS='
'
		output="$(cat "$test" | /jqpaths)"
		for key in $(echo "$output" | jq -r '. | keys[]') ; do
			expected=$(echo "$output" | jq -r --arg k "$key" '.[$k]')
			actual=$(cat "$test" | jq "$key")
			if [ "$expected" != "$actual" ] ; then
				echo "FAILED:"
				echo "Expected: '$expected'"
				echo "Actual:   '$actual'"
				exit 1
			fi
		done
		echo -e "\tPASSED"
	)
done
